apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-finance-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-finance"
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-users-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mysql-users"